language: go

go:
  - 1.8
  - 1.9
  - 1.10
  - tip

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

install: (cd netconf; go get -d -v ./... && go build -v ./...)
before_script:
  - cd netconf
  - go vet ./...
